modLoader = "javafml"
loaderVersion = "[4,)"
license = "BSD-3-Clause + CC BY-NC-SA 4.0"

[[mods]]
modId = "kaleidoscope_grilling"
version = "${version}"
displayName = "Kaleidoscope Grilling"
logoFile = "kaleidoscope_grilling_logo.png"
authors = "breezeth"
description = '''为《森罗物语：厨房》扩展热食、风味油料、新食材与炭火烧烤。
An expansion for Kaleidoscope Cookery featuring hot food, flavorful oils, new ingredients, and charcoal grilling.

【致谢 / Credits】
美术 / Art：Ao2333
策划 / Design：猫猫子、一年
测试 / Testing：酒狐玩具屋服务器、hutao、uwjsakdj、可可'''

[[mixins]]
config = "kaleidoscope_grilling.mixins.json"

[[dependencies.kaleidoscope_grilling]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kaleidoscope_grilling]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kaleidoscope_grilling]]
modId = "kaleidoscope_cookery"
type = "required"
versionRange = "[1.4.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kaleidoscope_grilling]]
modId = "create"
type = "optional"
versionRange = "[6.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kaleidoscope_grilling]]
modId = "touhou_little_maid"
type = "optional"
versionRange = "[1.5.3,)"
ordering = "AFTER"
side = "BOTH"
