plugins {
    id 'net.neoforged.moddev' version '2.0.134'
}

def props = new Properties()
file('gradle.properties').withInputStream { props.load(it) }

version = props.getProperty('mod_version')
group = props.getProperty('maven_group')

base { archivesName = props.getProperty('archives_base_name') }

repositories {
    maven { url = 'https://maven.blamejared.com' }
    exclusiveContent {
        forRepository {
            maven {
                name = 'Modrinth'
                url = 'https://api.modrinth.com/maven'
            }
        }
        filter { includeGroup 'maven.modrinth' }
    }
}

sourceSets.main.resources.srcDir rootProject.file('common/src/main/resources')

neoForge {
    version = props.getProperty('neo_version')
    runs {
        client { client(); gameDirectory = project.file('runs/client') }
        server { server(); gameDirectory = project.file('runs/server'); programArgument('--nogui') }
    }
    mods {
        kaleidoscope_grilling { sourceSet sourceSets.main }
    }
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    inputs.property 'version', project.version
    filesMatching('META-INF/neoforge.mods.toml') { expand version: inputs.properties.version }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
}

dependencies {
    implementation 'maven.modrinth:v17FatAc:TqaHu4Ma'
    compileOnly 'mezz.jei:jei-1.21.1-common-api:19.27.0.340'
    compileOnly 'mezz.jei:jei-1.21.1-neoforge-api:19.27.0.340'
    compileOnly 'maven.modrinth:jade:15.10.5+neoforge'
}

java { toolchain.languageVersion = JavaLanguageVersion.of(21) }

tasks.withType(Jar).configureEach {
    archiveFileName = "kaleidoscope_grilling-${project.version}-neoforge1.21.1.jar"
    from(rootProject.file('LICENSE-CODE'))
    from(rootProject.file('LICENSE-ASSETS'))
    from(rootProject.file('NOTICE'))
}
