modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "kaleidoscope_grilling"
version = "${version}"
displayName = "Kaleidoscope Grilling"
authors = "breezeth"
description = '''An expansion for Kaleidoscope Cookery focused on grilling and skewers.'''

[[mixins]]
config = "kaleidoscope_grilling.mixins.json"

[[dependencies.kaleidoscope_grilling]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kaleidoscope_grilling]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kaleidoscope_grilling]]
modId = "kaleidoscope_cookery"
type = "required"
versionRange = "[1.3.0,)"
ordering = "AFTER"
side = "BOTH"
