org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.daemon=true
minecraft_version=1.20.1
forge_version=47.4.0
create_version=6.0.6-168
ponder_version=1.0.80
flywheel_version=1.0.4
registrate_version=MC1.20-1.3.3
touhou_little_maid_version=1.5.3-forge+mc1.20.1
mod_version=1.1.1a
maven_group=cn.breezeth
archives_base_name=kaleidoscope_grilling
